management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
management.security.enabled: false
server:
  port: 8080
spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://mongo-trazabilidad:27017/trazabilidad_db}
